version: "8.0.0"
integrations:
  - type: ucv-ext-launch
    attributes:
      auto-config: true
    configs:
      name: Launch Integration
      loggingLevel: DEBUG
      deltaTime: '2023-05-15T18:30:00.000Z'
      # Additional integration-specific fields for Launch Integration